import requests
import pandas as pd
import numpy as np
import ast

class Uniprot:
    '''Given a Uniprot ID, this class can be used to fetch reference structure attributes such as Domains, Domain Architecture, Gene name, Reference sequence from Uniprot for specie of interest and returns a Domain reference csv file'''
    
    def __init__(self, UniProt_ID):
        self.UniProt_ID = UniProt_ID

    def Domains(self):
        res = requests.get(f'http://www.ebi.ac.uk/proteins/api/proteins/{self.UniProt_ID}').json() 
        gene = res['id']
        get_dom = []
        if 'features' in res.keys():
            for i in range(len(res['features'])):
                s = res['features'][i]
                for k, v in s.items():
                    if k == 'type':
                        if v == 'DOMAIN':
                            start = s['begin']
                            end = s['end']
                            name = s['description']
                            header = self.UniProt_ID+':'+gene+':'+name+':'+start+':'+end
                            #print(header)
                            get_dom.append(header)                    
        else:
            get_dom.append('None')
        return(get_dom)
    
    def DomainArchitecture(self):
        res = requests.get(f'http://www.ebi.ac.uk/proteins/api/proteins/{self.UniProt_ID}').json() 
        gene = res['id']
        get_dom = []
        domdict = {}
        if 'features' in res.keys():
            for i in range(len(res['features'])):
                s = res['features'][i]
                for k, v in s.items():
                    if k == 'type':
                        if v == 'DOMAIN':
                            start = s['begin']
                            end = s['end']
                            name = s['description']
                            header = self.UniProt_ID+':'+gene+':'+name+':'+start+':'+end
                            get_dom.append(header)  
                            domdict[start] = end, name
                    
        sorted_dict = dict(sorted(domdict.items(),reverse=True))
        domain_arch = []
        for key, value in sorted_dict.items():
            sort_start = key
            sort_end = value[0]
            domain = value[1]
            domain_arch.append(domain)
            
        if len(domain_arch) > 1:
            final_domarch = '|'.join(domain_arch)   
        else:
            final_domarch = domain
        #print('{count} number of domains with Architecture {Arch}'.format(count=len(domain_arch),Arch = final_domarch))  
        return(final_domarch)
    
    def Gene(self):
        get_url = requests.get(f'http://www.ebi.ac.uk/proteins/api/proteins/{self.UniProt_ID}')
        if get_url.status_code == 200:
            response = get_url.json()
            gene = response['id']
        else:
            gene = 'None'
        return(gene)

    def Specie(self):
        get_url = requests.get(f'http://www.ebi.ac.uk/proteins/api/proteins/{self.UniProt_ID}')
        if get_url.status_code == 200:
            response = get_url.json()
            specie = response['organism']['names'][0]['value']
        else:
            specie = 'None'
        return(specie)
    
    def RefSeq(self):
        get_url = requests.get(f'http://www.ebi.ac.uk/proteins/api/proteins/{self.UniProt_ID}')
        if get_url.status_code == 200:
            response = get_url.json()
            if 'sequence' in response.keys():
                seq = (response['sequence']['sequence'])
        else:
            seq = 'None'                 
        return(seq)
        
def makeRefFile(Uniprot_IDs, outputFile):
    '''Makes a Domain Reference file
    
    Parameters
    ----------
    Uniprot_IDs : list
        list of Uniprot Accession IDs generated by InterPro.py
    outputFile : string
        name of the output file
        
    Attributes
    ----------
        UPROT_Accession : Uniprot Accession ID
        Gene : gene name
        Domain Boundaries : reference domain boundary ranges with its start and end positions
        Ref Sequence : Reference sequence
        Domain Architecture : Domains found within the protein sequence arranged from N ter to C ter
        Specie : Scientific name 
        
    Returns
    -------
        output_df: pandas dataframe
            the dataframe that is written to the output .csv Domain reference file with all attributes'''
    
    
    Domain_list = []
    Gene_list = []
    Refseq_list = []
    Domain_Arch = []
    Specie_list = []
    #print('Fetch successful for Uniprot IDs :\n')
    for ID in Uniprot_IDs:
        instance = Uniprot(ID)
        DOMAIN = Uniprot.Domains(instance)
        GENE = Uniprot.Gene(instance)
        REFSEQ = Uniprot.RefSeq(instance)
        DOMAIN_ARCH = Uniprot.DomainArchitecture(instance)
        SPECIE = Uniprot.Specie(instance)
        
        Domain_list.append(DOMAIN)
        Gene_list.append(GENE)
        Refseq_list.append(REFSEQ)
        Domain_Arch.append(DOMAIN_ARCH)
        Specie_list.append(SPECIE)
        print(ID)
        
    df = pd.DataFrame(columns=['UPROT Accession','Gene','Domain Boundaries','Ref Sequence','Domain Architecture', 'Specie'])
    df['UPROT Accession'] = UniProt_IDs
    df['Gene'] = Gene_list
    df['Domain Boundaries'] = Domain_list
    df['Ref Sequence'] = Refseq_list
    df['Domain Architecture'] = Domain_Arch
    df['Specie'] = Specie_list
    df.index = np.arange(1, len(df) + 1)
    df.to_csv(outputFile, index=False)
    print('Domain Reference File successfully created!')
    
def PDB_IDs(UniProt_ID):
    '''Returns a list of PDB IDs that are associated to a specific Uniprot ID
    
    Parameters
    ----------
        UniProt_ID : Uniprot Accession ID used to pull a list of PDB IDs
        
    Returns
    -------
        PDB_IDs : List of PDB IDs'''
    
    PDB_IDs = []
    URL = f'https://www.ebi.ac.uK/proteins/api/proteins/{UniProt_ID}'
    try:
        response = requests.get(URL)
        data = response.json()
        for i in range(len(data['dbReferences'])):

            reftype = data['dbReferences'][i]['type']
            PDB_ID = data['dbReferences'][i]['id']

            if reftype == 'PDB':
                PDB_IDs.append(PDB_ID)
    
    except requests.exceptions.RequestException as err:
        print('ERROR:',err)
        
    print('Found {count} PDB IDs for {uID}'.format(count = len(PDB_IDs), uID = UniProt_ID))
    return(PDB_IDs)